version: "3.8"

name: kafka-cluster

services:
  kafka1:
    container_name: kafka1
    env_file:
      - .env
    image: "bitnami/kafka:latest"
    networks:
      - kafka
    ports:
      - ${KAFKA_BROKER_1_EXTERNAL_PORT}:${KAFKA_BROKER_1_EXTERNAL_PORT}
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=fZSmOdmYTEGGHzaVPoafYw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:${KAFKA_CONTROLLER_PORT},2@kafka2:${KAFKA_CONTROLLER_PORT},3@kafka3:${KAFKA_CONTROLLER_PORT}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_BROKER_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_BROKER_1_EXTERNAL_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:${KAFKA_BROKER_PORT},EXTERNAL://${DOCKER_HOST_IP:-localhost}:${KAFKA_BROKER_1_EXTERNAL_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - .volumes:/kafka/server-1:/bitnami/kafka

  kafka2:
    container_name: kafka2
    env_file:
      - .env
    image: "bitnami/kafka:latest"
    networks:
      - kafka
    ports:
      - ${KAFKA_BROKER_2_EXTERNAL_PORT}:${KAFKA_BROKER_2_EXTERNAL_PORT}
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=fZSmOdmYTEGGHzaVPoafYw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:${KAFKA_CONTROLLER_PORT},2@kafka2:${KAFKA_CONTROLLER_PORT},3@kafka3:${KAFKA_CONTROLLER_PORT}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_BROKER_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_BROKER_2_EXTERNAL_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:${KAFKA_BROKER_PORT},EXTERNAL://${DOCKER_HOST_IP:-localhost}:${KAFKA_BROKER_2_EXTERNAL_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - .volumes:/kafka/server-2:/bitnami/kafka

  kafka3:
    container_name: kafka3
    env_file:
      - .env
    image: "bitnami/kafka:latest"
    networks:
      - kafka
    ports:
      - ${KAFKA_BROKER_3_EXTERNAL_PORT}:${KAFKA_BROKER_3_EXTERNAL_PORT}
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=fZSmOdmYTEGGHzaVPoafYw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:${KAFKA_CONTROLLER_PORT},2@kafka2:${KAFKA_CONTROLLER_PORT},3@kafka3:${KAFKA_CONTROLLER_PORT}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_BROKER_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_BROKER_3_EXTERNAL_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:${KAFKA_BROKER_PORT},EXTERNAL://${DOCKER_HOST_IP:-localhost}:${KAFKA_BROKER_3_EXTERNAL_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - .volumes:/kafka/server-3:/bitnami/kafka

networks:
  kafka:
    driver: bridge
    name: microservices_network