version: "3.8"

name: order-postgresdb

services:
  order-postgresdb:
    container_name: order-postgresdb
    image: "postgres"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_ORDER_DATABASE}
#      - POSTGRES_MULTIPLE_DATABASES= ${POSTGRES_STOCK_DATABASE},${POSTGRES_ORDER_DATABASE}
    networks:
      - order-db
    expose:
      - ${POSTGRESDB_DOCKER_ORDERDB_PORT}
    ports:
      - ${POSTGRESDB_LOCAL_ORDERDB_PORT}:${POSTGRESDB_DOCKER_ORDERDB_PORT}
    volumes:
#      - ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
      - .db:/var/lib/postgres/orderdb
    command: -p ${POSTGRESDB_DOCKER_ORDERDB_PORT}

networks:
  order-db:
    name: microservices_network
    external: true